[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['iceberg.vim']
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    let g:gitgutter_map_keys = 0
    nmap [g <Plug>GitGutterPrevHunk
    nmap ]g <Plug>GitGutterNextHunk
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
    nmap s <Nop>
    xmap s <Nop>
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
    let g:rooter_patterns = ['.svn/','.git/']
    let g:rooter_change_directory_for_non_project_files = 'current'
    let g:rooter_use_lcd = 1
'''
