[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim', 'shabadou.vim']
on_ft = ['python']
hook_source = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
