version: 2
tools:
  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'

  golint: &golint
    lint-command: 'golint'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'

  json-jq: &json-jq
    format-command: 'jq .'
    format-stdin: true

  shellcheck-lint: &shellcheck-lint
    lint-command: 'shellcheck -s bash -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  shfmt-format: &shfmt-format
    format-command: 'shfmt -ln bash -kp -i 2 -ci'
    format-stdin: true

languages:
  markdown:
    - <<: *markdown-markdownlint
  go:
    - <<: *golint
  json:
    - <<: *json-jq
  sh:
    - <<: *shellcheck-lint
    - <<: *shfmt-format
