version: 2
tools:
  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'

  shellcheck-lint: &shellcheck-lint
    lint-command: 'shellcheck -s bash -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  shfmt-format: &shfmt-format
    format-command: 'shfmt -ln bash -kr -i 2 -ci'
    format-stdin: true

languages:
  markdown:
    - <<: *markdown-markdownlint
  json:
    - <<: *json-fixjson
  sh:
    - <<: *shellcheck-lint
    - <<: *shfmt-format
