languages:
  markdown:
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
  go:
    lint-command: 'golint'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'
  json:
    format-command: 'jq .'
